services:
  backend:
    build:
      context: ./backend
    container_name: logs-metrics-backend
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/app/data
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/backend
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./frontend
      args:
        VITE_APP_BACKEND: http://localhost:8080/api/v1/
    container_name: logs-metrics-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  backend-data:
